
- type: application/vnd.dotmpe.project
  id: bvberkum/x-drone
  env: ENV_NAME=.. . ./env.sh
  scripts:

    build-1:
      - cp files/acme/Dockerfile _/drone-docker-plugin-1
      - cd _/drone-docker-plugin-1 && drone exec
      - rm _/drone-docker-plugin-1/Dockerfile
      - docker run --name acme_build --entrypoint /exe --workdir /tmp sandbox-3:5000/acme echo 'Thats all folks!'
      - docker commit acme_build acme:build
      - docker rm -f acme_build
    test-1:
      - docker pull sandbox-3:5000/acme
      - docker run -ti sandbox-3:5000/acme </dev/tty
    publish-1:
      - ' for tag in build-1 latest; do \
            docker tag acme freyr/acme:$tag; \
            docker push freyr/acme:$tag; done '

    build-2:
      - cd _/drone-docker-plugin-2 && drone exec
    test-2:
      - docker run -ti acme:build-2 </dev/tty
    publish-2:
      - ' for tag in build-2 latest; do \
            docker tag acme freyr/acme:$tag; \
            docker push freyr/acme:$tag; done '

- type: application/vnd.dotmpe.environment
  id: bvberkum/x-drone-main
  main: bvberkum/x-drone

